name: AvoidRcKb
version: '${project.version}'
main: com.axiumyu.avoidrckb.AvoidRcKb
api-version: '1.20'
load: STARTUP
commands:
  Distance:
    description: Your description
    usage: /distance <set> <distance>
    permission: AvoidRcKb.distance
